// <auto-generated />
using System;
using IncidentSheet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IncidentSheet.Migrations
{
    [DbContext(typeof(JokerDbContext))]
    [Migration("20190312003351_intial")]
    partial class intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IncidentSheet.Models.Joker", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Incident");

                    b.Property<DateTime>("IncidentDate");

                    b.Property<DateTime>("IncidentTime");

                    b.Property<string>("Summary");

                    b.Property<int>("Unit");

                    b.HasKey("ID");

                    b.ToTable("Jokers");
                });

            modelBuilder.Entity("IncidentSheet.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("JokerID");

                    b.Property<string>("UserName");

                    b.Property<string>("UserPassword");

                    b.HasKey("UserId");

                    b.HasIndex("JokerID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IncidentSheet.Models.User", b =>
                {
                    b.HasOne("IncidentSheet.Models.Joker")
                        .WithMany("Users")
                        .HasForeignKey("JokerID");
                });
#pragma warning restore 612, 618
        }
    }
}
